/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartelaBingo: typeof import('./src/components/CartelaBingo.vue')['default']
    DefaultLayout: typeof import('./src/components/DefaultLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TesteTeste: typeof import('./src/components/TesteTeste.vue')['default']
  }
}
